# Generated by Django 5.2.1 on 2025-06-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('cancelado', 'Cancelado'), ('atendido', 'Atendido'), ('nao_atendido', 'Não atendido')], default='agendado', max_length=20),
        ),
    ]
