# Generated by Django 5.2.1 on 2025-07-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_alter_agendamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('atendido', 'Atendido'), ('remarcado', 'Remarcado'), ('reagendado', 'Reagendado')], default='agendado', max_length=20),
        ),
    ]
