# Generated by Django 5.2.1 on 2025-07-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_alter_agendamento_confirmacao'),
        ('agendamento', '0005_agendamento_confirmacao'),
    ]

    operations = [
    ]
