# Generated by Django 5.2.1 on 2025-07-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
