# Generated by Django 5.2.1 on 2025-06-04 13:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodo', models.PositiveIntegerField(default=12)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adesao', models.DateField(default=datetime.date.today)),
                ('dia_vencimento', models.IntegerField(choices=[(5, 'Dia 5'), (10, 'Dia 10'), (15, 'Dia 15'), (20, 'Dia 20'), (25, 'Dia 25'), (30, 'Dia 30')])),
                ('valor_adesao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('numero_contrato', models.CharField(max_length=20, unique=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.plano')),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('data_vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('pago', 'Pago')], default='aberto', max_length=20)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.contrato')),
            ],
        ),
    ]
