# Generated by Django 5.2.1 on 2025-06-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
