# Generated by Django 5.2.1 on 2025-06-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_parcela_forma_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao', 'Cartão')], max_length=20),
        ),
    ]
