# Generated by Django 5.2.1 on 2025-06-08 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_parcela_forma_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('forma', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao_credito', 'Cartão de crédito'), ('cartao_debito', 'Cartão de dédito')], max_length=20)),
                ('plano_conta', models.CharField(choices=[('despesa_fixa', 'Despesa Fixa'), ('consultorio', 'Despesa do Consultório'), ('almoco_funcionario', 'Almoço Funcionário'), ('combustivel', 'Combustível'), ('outros', 'Outros')], default='outros', max_length=30)),
                ('observacao', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='parcela',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
