# Generated by Django 5.2.1 on 2025-06-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_caixa_alter_parcela_forma_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='forma',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao_credito', 'Cartão de crédito'), ('cartao_debito', 'Cartão de débito')], max_length=20),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao_credito', 'Cartão de crédito'), ('cartao_debito', 'Cartão de débito')], max_length=20, null=True),
        ),
    ]
