# Generated by Django 5.2.1 on 2025-06-08 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_alter_caixa_data_alter_caixa_forma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='valor_adesao',
        ),
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='plano',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='DESCRIÇÃO'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='NOME'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='periodo',
            field=models.PositiveIntegerField(default=12, verbose_name='PARCELAS'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='VALOR'),
        ),
    ]
