# Generated by Django 5.2.1 on 2025-06-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_remove_contrato_valor_adesao_alter_caixa_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='plano_conta',
            field=models.CharField(choices=[('despesa_fixa', 'Despesa Fixa'), ('consultorio', 'Despesa do Consultório'), ('almoco_funcionario', 'Almoço Funcionário'), ('combustivel', 'Combustível'), ('outros', 'Outros'), ('planos', 'Planos')], default='outros', max_length=30),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='Parcela'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('pago', 'Pago')], default=False, max_length=20),
        ),
    ]
