# Generated by Django 5.2.1 on 2025-06-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_alter_caixa_plano_conta_alter_parcela_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('pago', 'Pago')], default='aberto', max_length=20),
        ),
    ]
