# Generated by Django 5.2.1 on 2025-06-10 19:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_alter_parcela_status'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='status_contrato',
            field=models.CharField(blank=True, choices=[('ativo', 'ATIVO'), ('pendente', 'PENDENTE'), ('cancelado', 'CANCELADO')], max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_adesao',
            field=models.DateField(default=datetime.date.today, verbose_name='Adesão'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='dia_vencimento',
            field=models.IntegerField(choices=[(5, 'Dia 5'), (10, 'Dia 10'), (15, 'Dia 15'), (20, 'Dia 20'), (25, 'Dia 25'), (30, 'Dia 30')], verbose_name='Vencimento'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='numero_contrato',
            field=models.CharField(max_length=20, unique=True, verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.plano', verbose_name='Plano'),
        ),
    ]
