# Generated by Django 5.2.1 on 2025-07-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_contrato_status_contrato_alter_contrato_data_adesao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='plano_conta',
            field=models.CharField(choices=[('Consultorio', 'Despesa do Consultório'), ('Boletos', 'Boletos'), ('Outros', 'Outros'), ('Planos', 'Planos'), ('Procedimento', 'Procedimento Particular')], default='outros', max_length=30),
        ),
    ]
