# Generated by Django 5.2.1 on 2025-07-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_alter_caixa_plano_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
