# Generated by Django 5.2.1 on 2025-07-04 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_alter_caixa_forma_alter_parcela_forma_pagamento'),
        ('financeiro', '0011_parcela_valor_pago'),
    ]

    operations = [
    ]
